"""trias2

Revision ID: 770d77b1ec3d
Revises: 
Create Date: 2025-02-23 19:31:46.736991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770d77b1ec3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perros',
    sa.Column('id_perro', sa.Integer(), nullable=False),
    sa.Column('plaquita', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_perro'),
    sa.UniqueConstraint('plaquita')
    )
    op.drop_table('foro')
    op.drop_table('visitante')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitante',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_visit', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='visitante_pkey'),
    sa.UniqueConstraint('name_visit', name='visitante_name_visit_key')
    )
    op.create_table('foro',
    sa.Column('id_foro', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_foro', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('abreviado', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_foro', name='foro_pkey'),
    sa.UniqueConstraint('name_foro', name='foro_name_foro_key')
    )
    op.drop_table('perros')
    # ### end Alembic commands ###
